/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Daniel
 */
public class FormularioView extends javax.swing.JFrame {

    /**
     * Creates new form FormularioView
     */
    public FormularioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBG = new javax.swing.JPanel();
        PanelUsuario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        PanelAlquiler = new javax.swing.JPanel();
        lblSencilla = new javax.swing.JLabel();
        txtSencilla = new javax.swing.JTextField();
        lblDoble = new javax.swing.JLabel();
        lblSuite = new javax.swing.JLabel();
        txtDoble = new javax.swing.JTextField();
        txtSuite = new javax.swing.JTextField();
        lblPrecioSencilla = new javax.swing.JLabel();
        lblPrecioDoble = new javax.swing.JLabel();
        lblPrecioSuote = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrarAlquiler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel");
        setLocationByPlatform(true);
        setResizable(false);

        PanelBG.setBackground(new java.awt.Color(255, 255, 255));

        PanelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");

        txtNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblDocumento.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblDocumento.setForeground(new java.awt.Color(0, 0, 0));
        lblDocumento.setText("Documento:");

        txtDocumento.setBackground(new java.awt.Color(102, 102, 102));
        txtDocumento.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        lblEdad.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(0, 0, 0));
        lblEdad.setText("Edad:");

        txtEdad.setBackground(new java.awt.Color(102, 102, 102));
        txtEdad.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(255, 255, 255));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDocumento)
                            .addComponent(lblEdad))
                        .addGap(18, 18, 18)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelAlquiler.setBackground(new java.awt.Color(255, 255, 255));
        PanelAlquiler.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Alquiler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        lblSencilla.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblSencilla.setForeground(new java.awt.Color(0, 0, 0));
        lblSencilla.setText("Sencilla");

        txtSencilla.setBackground(new java.awt.Color(102, 102, 102));
        txtSencilla.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtSencilla.setForeground(new java.awt.Color(255, 255, 255));
        txtSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSencillaActionPerformed(evt);
            }
        });

        lblDoble.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblDoble.setForeground(new java.awt.Color(0, 0, 0));
        lblDoble.setText("Doble");

        lblSuite.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblSuite.setForeground(new java.awt.Color(0, 0, 0));
        lblSuite.setText("Suite");

        txtDoble.setBackground(new java.awt.Color(102, 102, 102));
        txtDoble.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtDoble.setForeground(new java.awt.Color(255, 255, 255));
        txtDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobleActionPerformed(evt);
            }
        });

        txtSuite.setBackground(new java.awt.Color(102, 102, 102));
        txtSuite.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtSuite.setForeground(new java.awt.Color(255, 255, 255));
        txtSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuiteActionPerformed(evt);
            }
        });

        lblPrecioSencilla.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblPrecioSencilla.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioSencilla.setText("40.000");

        lblPrecioDoble.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblPrecioDoble.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioDoble.setText("60.000");

        lblPrecioSuote.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblPrecioSuote.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioSuote.setText("80.000");

        javax.swing.GroupLayout PanelAlquilerLayout = new javax.swing.GroupLayout(PanelAlquiler);
        PanelAlquiler.setLayout(PanelAlquilerLayout);
        PanelAlquilerLayout.setHorizontalGroup(
            PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDoble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSuite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSencilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSencilla, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(txtDoble)
                    .addComponent(txtSuite))
                .addGap(35, 35, 35)
                .addGroup(PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPrecioDoble, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(lblPrecioSencilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioSuote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAlquilerLayout.setVerticalGroup(
            PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlquilerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSencilla)
                    .addComponent(txtSencilla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioSencilla))
                .addGap(18, 18, 18)
                .addGroup(PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoble)
                    .addComponent(txtDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioDoble))
                .addGap(18, 18, 18)
                .addGroup(PanelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuite)
                    .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioSuote))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegistrarAlquiler.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarAlquiler.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnRegistrarAlquiler.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAlquiler.setText("Registrar Alquiler");

        javax.swing.GroupLayout PanelBGLayout = new javax.swing.GroupLayout(PanelBG);
        PanelBG.setLayout(PanelBGLayout);
        PanelBGLayout.setHorizontalGroup(
            PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarAlquiler)
                .addGap(40, 40, 40)
                .addComponent(btnLimpiar)
                .addGap(43, 43, 43))
        );
        PanelBGLayout.setVerticalGroup(
            PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBGLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(PanelAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(PanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegistrarAlquiler))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSencillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSencillaActionPerformed

    private void txtDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobleActionPerformed

    private void txtSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuiteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelAlquiler;
    public javax.swing.JPanel PanelBG;
    public javax.swing.JPanel PanelUsuario;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnRegistrarAlquiler;
    public javax.swing.JLabel lblDoble;
    public javax.swing.JLabel lblDocumento;
    public javax.swing.JLabel lblEdad;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblPrecioDoble;
    public javax.swing.JLabel lblPrecioSencilla;
    public javax.swing.JLabel lblPrecioSuote;
    public javax.swing.JLabel lblSencilla;
    public javax.swing.JLabel lblSuite;
    public javax.swing.JTextField txtDoble;
    public javax.swing.JTextField txtDocumento;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtSencilla;
    public javax.swing.JTextField txtSuite;
    // End of variables declaration//GEN-END:variables
}
